In [162]:
import pandas as pd
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import *

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OutputCodeClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

from sklearn.neighbors import KDTree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import RadiusNeighborsClassifier

from sklearn.neural_network import MLPClassifier

from sklearn.svm import LinearSVC

from df_functions import *

In [143]:
df = pd.read_csv('../data/df_for_model.csv')

In [144]:
X_train, X_test, y_train, y_test = get_Xy_train_test(df)

y Shape: (2076,)
X Shape: (2076, 31)
X_train Shape: (1966, 31)
X_test Shape: (110, 31)
y_train Shape: (1966,)
y_test Shape: (110,)


/home/guess/lots-of-data/src/df_functions.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  df['diff_bin'] = pd.cut(df['diff'], bins=bins, labels=labels)


In [283]:
LDA_clf = LinearDiscriminantAnalysis(solver = 'svd').fit(X_train, y_train)
LDA_scores = cross_validation_process(LDA_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 77.98%

Standard Deviation = 0.15

Scores(average_precision):
 [0.84166667 0.64960317 0.66071429 0.925      0.91111111 0.925
 0.65952381 0.82111111 0.68619048 0.49777778 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.72      0.69      0.71        52
         1.0       0.73      0.76      0.75        58

   micro avg       0.73      0.73      0.73       110
   macro avg       0.73      0.73      0.73       110
weighted avg       0.73      0.73      0.73       110


confusion_matrix:
[[36 16]
 [14 44]]

confusion_matrix accuracy: 72.72727272727273%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variabl

In [282]:
QDA_clf = QuadraticDiscriminantAnalysis(reg_param=1).fit(X_train, y_train)
QDA_scores = cross_validation_process(QDA_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 83.09%

Standard Deviation = 0.091

Scores(average_precision):
 [0.7645202  0.75138889 0.84329004 0.94285714 0.92666667 0.87619048
 0.71       0.82619048 0.75952381 0.73928571 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.71      0.67      0.69        52
         1.0       0.72      0.76      0.74        58

   micro avg       0.72      0.72      0.72       110
   macro avg       0.72      0.72      0.72       110
weighted avg       0.72      0.72      0.72       110


confusion_matrix:
[[35 17]
 [14 44]]

confusion_matrix accuracy: 71.81818181818181%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are coll

In [281]:
ada_clf = AdaBoostClassifier(n_estimators=100, learning_rate=0.25, random_state=9).fit(X_train, y_train)
ada_scores = cross_validation_process(ada_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 75.96%

Standard Deviation = 0.157

Scores(average_precision):
 [0.82840909 0.65694444 0.76203704 0.90285714 0.885      0.96666667
 0.62952381 0.52539683 0.85285714 0.46928571 0.87666667]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.74      0.71      0.73        52
         1.0       0.75      0.78      0.76        58

   micro avg       0.75      0.75      0.75       110
   macro avg       0.74      0.74      0.74       110
weighted avg       0.75      0.75      0.75       110


confusion_matrix:
[[37 15]
 [13 45]]

confusion_matrix accuracy: 74.54545454545455%
-----------------------------------------------------------------------


In [293]:
XTsC_clf = ExtraTreesClassifier(n_estimators=1000, criterion='entropy',  n_jobs=-2, 
                                random_state=9, class_weight='balanced').fit(X_train, y_train)
XTsC_score = cross_validation_process(XTsC_clf, X_test, y_test)

Average Accuracy(average_precision) = 67.94%

Standard Deviation = 0.069

Scores(average_precision):
 [0.67400031 0.79456909 0.70457092 0.63297498 0.59100844]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.67      0.71      0.69        52
         1.0       0.73      0.69      0.71        58

   micro avg       0.70      0.70      0.70       110
   macro avg       0.70      0.70      0.70       110
weighted avg       0.70      0.70      0.70       110


confusion_matrix:
[[37 15]
 [18 40]]

confusion_matrix accuracy: 70.0%
-----------------------------------------------------------------------


In [290]:
grad_boost_clf = GradientBoostingClassifier(n_estimators=10000, learning_rate=0.1,
                                            max_depth=50, random_state=9,
                                            n_iter_no_change=50).fit(X_train, y_train)
grad_boost_score = cross_validation_process(grad_boost_clf, X_test, y_test)

Average Accuracy(average_precision) = 65.52%

Standard Deviation = 0.079

Scores(average_precision):
 [0.62468317 0.78000306 0.66111666 0.53571429 0.67465867]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.63      0.52      0.57        52
         1.0       0.63      0.72      0.67        58

   micro avg       0.63      0.63      0.63       110
   macro avg       0.63      0.62      0.62       110
weighted avg       0.63      0.63      0.62       110


confusion_matrix:
[[27 25]
 [16 42]]

confusion_matrix accuracy: 62.727272727272734%
-----------------------------------------------------------------------


In [280]:
rand_frst_clf = RandomForestClassifier(n_estimators=100, criterion='entropy', n_jobs=-2, 
                                       random_state=9).fit(X_train, y_train)

rand_frst_score = cross_validation_process(rand_frst_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 79.6%

Standard Deviation = 0.154

Scores(average_precision):
 [0.8218254  0.66071429 0.74027778 0.96666667 0.92666667 0.96666667
 0.72952381 0.58888889 0.87666667 0.51111111 0.96666667]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.67      0.69      0.68        52
         1.0       0.71      0.69      0.70        58

   micro avg       0.69      0.69      0.69       110
   macro avg       0.69      0.69      0.69       110
weighted avg       0.69      0.69      0.69       110


confusion_matrix:
[[36 16]
 [18 40]]

confusion_matrix accuracy: 69.0909090909091%
-----------------------------------------------------------------------


In [279]:
gpc_rbf_clf = GaussianProcessClassifier(n_jobs=-2, max_iter_predict=300, 
                                        random_state=9).fit(X_train, y_train)
gpc_rbf_score = cross_validation_process(gpc_rbf_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 81.43%

Standard Deviation = 0.126

Scores(average_precision):
 [0.79960317 0.69305556 0.69126984 1.         0.90285714 0.92666667
 0.80833333 0.70873016 0.82111111 0.60539683 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.71      0.75      0.73        52
         1.0       0.76      0.72      0.74        58

   micro avg       0.74      0.74      0.74       110
   macro avg       0.74      0.74      0.74       110
weighted avg       0.74      0.74      0.74       110


confusion_matrix:
[[39 13]
 [16 42]]

confusion_matrix accuracy: 73.63636363636363%
-----------------------------------------------------------------------


In [278]:
lgst_reg_clf = LogisticRegression(penalty='l2', tol=0.00001,
                                  class_weight='balanced', random_state=9, 
                                  solver='newton-cg', n_jobs=-2).fit(X_train, y_train)

lgst_reg_score = cross_validation_process(lgst_reg_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 81.48%

Standard Deviation = 0.111

Scores(average_precision):
 [0.81071429 0.66051587 0.86174242 0.94285714 0.90285714 0.91111111
 0.71       0.73111111 0.75952381 0.67261905 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.70      0.73      0.72        52
         1.0       0.75      0.72      0.74        58

   micro avg       0.73      0.73      0.73       110
   macro avg       0.73      0.73      0.73       110
weighted avg       0.73      0.73      0.73       110


confusion_matrix:
[[38 14]
 [16 42]]

confusion_matrix accuracy: 72.72727272727273%
-----------------------------------------------------------------------


In [277]:
lgst_reg_cv_clf = LogisticRegressionCV(Cs=20, penalty='l2', tol=0.00001, cv=7,
                                       class_weight='balanced', random_state=9, 
                                       solver='newton-cg', n_jobs=-2).fit(X_train, y_train)
lgst_reg_cv_score = cross_validation_process(lgst_reg_cv_clf, X_test, y_test, cv=11)

/home/guess/.local/lib/python3.6/site-packages/scipy/optimize/linesearch.py:313: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/utils/optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')


Average Accuracy(average_precision) = 83.09%

Standard Deviation = 0.091

Scores(average_precision):
 [0.7645202  0.75138889 0.84329004 0.94285714 0.92666667 0.87619048
 0.71       0.82619048 0.75952381 0.73928571 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.69      0.67      0.68        52
         1.0       0.71      0.72      0.72        58

   micro avg       0.70      0.70      0.70       110
   macro avg       0.70      0.70      0.70       110
weighted avg       0.70      0.70      0.70       110


confusion_matrix:
[[35 17]
 [16 42]]

confusion_matrix accuracy: 70.0%
-----------------------------------------------------------------------


In [276]:
ridge_clf = RidgeClassifier(alpha=20.0, class_weight='balanced', solver='sparse_cg', 
                            random_state=9).fit(X_train, y_train)
ridge_score = cross_validation_process(ridge_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 83.03%

Standard Deviation = 0.095

Scores(average_precision):
 [0.80694444 0.71904762 0.82840909 0.94285714 0.92666667 0.91111111
 0.71       0.78928571 0.75952381 0.73928571 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.72      0.65      0.69        52
         1.0       0.71      0.78      0.74        58

   micro avg       0.72      0.72      0.72       110
   macro avg       0.72      0.71      0.72       110
weighted avg       0.72      0.72      0.72       110


confusion_matrix:
[[34 18]
 [13 45]]

confusion_matrix accuracy: 71.81818181818181%
-----------------------------------------------------------------------


In [275]:
ridge_cv_clf = RidgeClassifierCV(scoring='average_precision', cv=20, class_weight='balanced').fit(X_train, y_train)
ridge_cv_score = cross_validation_process(ridge_cv_clf, X_test, y_test, cv=11)

/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/metrics/ranking

Average Accuracy(average_precision) = 80.4%

Standard Deviation = 0.137

Scores(average_precision):
 [0.81071429 0.69126984 0.86174242 0.925      0.91111111 0.925
 0.68619048 0.77539683 0.75952381 0.49777778 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.71      0.65      0.68        52
         1.0       0.71      0.76      0.73        58

   micro avg       0.71      0.71      0.71       110
   macro avg       0.71      0.71      0.71       110
weighted avg       0.71      0.71      0.71       110


confusion_matrix:
[[34 18]
 [14 44]]

confusion_matrix accuracy: 70.9090909090909%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [270]:
SGD_clf = SGDClassifier(loss='squared_hinge', max_iter=10000, shuffle=False, 
                        n_jobs=-2, random_state=9, n_iter_no_change=50, 
                        class_weight='balanced').fit(X_train, y_train)

SGD_score = cross_validation_process(SGD_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 82.06%

Standard Deviation = 0.133

Scores(average_precision):
 [0.80694444 0.67638889 0.87662338 1.         0.94285714 0.91111111
 0.78619048 0.69444444 0.75952381 0.57261905 1.        ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.69      0.77      0.73        52
         1.0       0.77      0.69      0.73        58

   micro avg       0.73      0.73      0.73       110
   macro avg       0.73      0.73      0.73       110
weighted avg       0.73      0.73      0.73       110


confusion_matrix:
[[40 12]
 [18 40]]

confusion_matrix accuracy: 72.72727272727273%
-----------------------------------------------------------------------


In [274]:
ovo_clf = OneVsOneClassifier(LinearSVC(penalty='l2', loss='hinge', dual=True,
                                       C=32.0, class_weight='balanced',
                                       random_state=9)).fit(X_train, y_train)
ovo_score = cross_validation_process(ovo_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 52.12%

Standard Deviation = 0.143

Scores(average_precision):
 [0.85238095 0.42622655 0.68257576 0.37055556 0.47555556 0.545
 0.65873016 0.41904762 0.40349206 0.46928571 0.43015873]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.55      0.87      0.67        52
         1.0       0.75      0.36      0.49        58

   micro avg       0.60      0.60      0.60       110
   macro avg       0.65      0.61      0.58       110
weighted avg       0.65      0.60      0.58       110


confusion_matrix:
[[45  7]
 [37 21]]

confusion_matrix accuracy: 60.0%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iteratio

In [273]:
ovr_clf = OneVsRestClassifier(LinearSVC(penalty='l2', loss='hinge', dual=True,
                                        C=32.0, random_state=9)).fit(X_train, y_train)
ovr_score = cross_validation_process(ovr_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 52.12%

Standard Deviation = 0.143

Scores(average_precision):
 [0.85238095 0.42622655 0.68257576 0.37055556 0.47555556 0.545
 0.65873016 0.41904762 0.40349206 0.46928571 0.43015873]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.55      0.87      0.67        52
         1.0       0.75      0.36      0.49        58

   micro avg       0.60      0.60      0.60       110
   macro avg       0.65      0.61      0.58       110
weighted avg       0.65      0.60      0.58       110


confusion_matrix:
[[45  7]
 [37 21]]

confusion_matrix accuracy: 60.0%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iteratio

In [ ]:
OC_clf = OutputCodeClassifier().fit(X_train, y_train)
OC_score = cross_validation_process(OC_clf, X_test, y_test)

In [ ]:
dec_tree_clf = DecisionTreeClassifier().fit(X_train, y_train)
dec_tree_score = cross_validation_process(dec_tree_clf, X_test, y_test)

In [188]:
ET_clf = ExtraTreeClassifier(criterion='entropy', random_state=9, 
                             class_weight='balanced').fit(X_train, y_train)
ET_score = cross_validation_process(ET_clf, X_test, y_test)

Average Accuracy(average_precision) = 59.07%

Standard Deviation = 0.076

Scores(average_precision):
 [0.56086957 0.5771526  0.73484848 0.56980519 0.51082251]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.59      0.58      0.58        52
         1.0       0.63      0.64      0.63        58

   micro avg       0.61      0.61      0.61       110
   macro avg       0.61      0.61      0.61       110
weighted avg       0.61      0.61      0.61       110


confusion_matrix:
[[30 22]
 [21 37]]

confusion_matrix accuracy: 60.909090909090914%
-----------------------------------------------------------------------


In [193]:
brnl_clf = BernoulliNB().fit(X_train, y_train)
brnl_score = cross_validation_process(brnl_clf, X_test, y_test)

Average Accuracy(average_precision) = 57.35%

Standard Deviation = 0.092

Scores(average_precision):
 [0.6676276  0.5060393  0.60415765 0.66015125 0.4294104 ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.51      0.54      0.52        52
         1.0       0.56      0.53      0.55        58

   micro avg       0.54      0.54      0.54       110
   macro avg       0.54      0.54      0.54       110
weighted avg       0.54      0.54      0.54       110


confusion_matrix:
[[28 24]
 [27 31]]

confusion_matrix accuracy: 53.63636363636364%
-----------------------------------------------------------------------


In [155]:
gaussian_nb_clf = GaussianNB().fit(X_train, y_train)
gaussian_nb_score = cross_validation_process(gaussian_nb_clf, X_test, y_test)

Average Accuracy(average_precision) = 56.21%

Standard Deviation = 0.078

Scores(average_precision):
 [0.5756423  0.54630845 0.61900742 0.64791202 0.42170414]

Classification Report:
              precision    recall  f1-score   support

         0.0       1.00      0.04      0.07        52
         1.0       0.54      1.00      0.70        58

   micro avg       0.55      0.55      0.55       110
   macro avg       0.77      0.52      0.39       110
weighted avg       0.76      0.55      0.40       110


confusion_matrix:
[[ 2 50]
 [ 0 58]]

confusion_matrix accuracy: 54.54545454545454%
-----------------------------------------------------------------------


In [157]:
multinomial_nb_clf = MultinomialNB(alpha=1).fit(X_train, y_train)
ml_nb_scores = cross_validation_process(multinomial_nb_clf, X_test, y_test)

Average Accuracy(average_precision) = 55.39%

Standard Deviation = 0.085

Scores(average_precision):
 [0.6619818  0.53103503 0.56673812 0.60132616 0.40851047]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.56      0.56      0.56        52
         1.0       0.60      0.60      0.60        58

   micro avg       0.58      0.58      0.58       110
   macro avg       0.58      0.58      0.58       110
weighted avg       0.58      0.58      0.58       110


confusion_matrix:
[[29 23]
 [23 35]]

confusion_matrix accuracy: 58.18181818181818%
-----------------------------------------------------------------------


In [271]:
KNN_clf = KNeighborsClassifier(leaf_size=45, n_jobs=-2).fit(X_train, y_train)
KNN_score = cross_validation_process(KNN_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 78.88%

Standard Deviation = 0.122

Scores(average_precision):
 [0.72626263 0.66468254 0.78571429 1.         0.87111111 0.86285714
 0.67238095 0.69761905 0.82111111 0.60833333 0.96666667]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.67      0.73      0.70        52
         1.0       0.74      0.67      0.70        58

   micro avg       0.70      0.70      0.70       110
   macro avg       0.70      0.70      0.70       110
weighted avg       0.70      0.70      0.70       110


confusion_matrix:
[[38 14]
 [19 39]]

confusion_matrix accuracy: 70.0%
-----------------------------------------------------------------------


In [272]:
MLP_clf = MLPClassifier(solver='lbfgs', random_state=9).fit(X_train, y_train)
MLP_score = cross_validation_process(MLP_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 65.83%

Standard Deviation = 0.101

Scores(average_precision):
 [0.81051587 0.49814815 0.64051227 0.69619048 0.58       0.67833333
 0.68619048 0.78928571 0.65444444 0.47777778 0.72952381]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.69      0.71      0.70        52
         1.0       0.73      0.71      0.72        58

   micro avg       0.71      0.71      0.71       110
   macro avg       0.71      0.71      0.71       110
weighted avg       0.71      0.71      0.71       110


confusion_matrix:
[[37 15]
 [17 41]]

confusion_matrix accuracy: 70.9090909090909%
-----------------------------------------------------------------------


In [ ]:
# classification_scoring = ['accuracy', 'balanced_accuracy', 'average_precision',
#                           'brier_score_loss', 'f1', 'f1_micro', 'f1_macro',
#                           'f1_weighted', 'neg_log_loss', 'precision',
#                           'recall', 'roc_auc']

In [ ]:
# classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="linear", C=0.025),
#     SVC(gamma=2, C=1),
#     GaussianProcessClassifier(1.0 * RBF(1.0)),
#     DecisionTreeClassifier(max_depth=5),
#     RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
#     MLPClassifier(alpha=1),
#     AdaBoostClassifier(),
#     GaussianNB(),
#     QuadraticDiscriminantAnalysis()]

In [ ]:
# clf1 = LogisticRegression(solver='lbfgs', multi_class='multinomial',
#                           random_state=1)
# clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
# clf3 = GaussianNB()

# eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

# for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
#     scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
#     print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

In [ ]:
# clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
#     random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = RandomForestClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean() > 0.999

In [ ]:
# est = GradientBoostingRegressor
# mean_squared_error(y_test, est.predict(X_test))  
# clf.score(X_test, y_test)