# Running all Classification Models to get the best predictions
## Then, moving on to Neural Networks to get "Better Predictions"

In [101]:
import pandas as pd
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import *

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeClassifier

from sklearn.neighbors import KDTree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import RadiusNeighborsClassifier

from sklearn.neural_network import MLPClassifier

from sklearn.svm import LinearSVC

from df_functions import *

from warnings import filterwarnings
filterwarnings('ignore')

In [96]:
df = pd.read_csv('../data/df_for_model.csv')

In [97]:
X_train, X_test, y_train, y_test = get_Xy_train_test(df)

y Shape: (2076,)
X Shape: (2076, 31)
X_train Shape: (1964, 31)
X_test Shape: (112, 31)
y_train Shape: (1964,)
y_test Shape: (112,)


### Linear Discriminant Analysis

In [98]:
X_train

array([[1, 31, 0, ..., 0, 0, 0],
       [0, 117, 0, ..., 0, 0, 0],
       [0, 15, 0, ..., 0, 0, 0],
       ...,
       [0, 79, 0, ..., 0, 1, 0],
       [0, 69, 0, ..., 0, 1, 0],
       [1, 64, 0, ..., 0, 1, 0]], dtype=object)

In [102]:
LDA_clf = LinearDiscriminantAnalysis(solver = 'lsqr', shrinkage='auto').fit(X_train, y_train)
LDA_scores = cross_validation_process(LDA_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=81.2%
Standard_Deviation=0.107
Scores(average_precision)=[0.883 0.713 0.924 0.917 0.882 0.925 0.686 0.709 0.76  0.63  0.903]
No Feature Importances
Prediction_Confusion_Matrix=
[[35 17]
 [15 45]]
Prediction_Accuracy=71.43%


### Quadratic Discriminant Analysis

Best results with:
- reg_param = 0.26055
- reg_param = 0.36968
- reg_param = 0.25357
- reg_param = 0.43083
- reg_param = 0.72097

In [103]:
reg_param = [0.26055, 0.36968, 0.25357, 0.43083, 0.72097]
for num in reg_param:
    QDA_clf = QuadraticDiscriminantAnalysis(reg_param=num).fit(X_train, y_train)
    QDA_scores = cross_validation_process(QDA_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=83.34%
Standard_Deviation=0.089
Scores(average_precision)=[0.811 0.749 0.821 0.911 0.931 0.911 0.71  0.759 0.826 0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[31 21]
 [12 48]]
Prediction_Accuracy=70.54%
Average_Accuracy(average_precision)=83.89%
Standard_Deviation=0.09
Scores(average_precision)=[0.852 0.749 0.821 0.911 0.948 0.911 0.71  0.826 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[31 21]
 [12 48]]
Prediction_Accuracy=70.54%
Average_Accuracy(average_precision)=83.32%
Standard_Deviation=0.087
Scores(average_precision)=[0.811 0.76  0.821 0.911 0.917 0.911 0.71  0.759 0.826 0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[31 21]
 [11 49]]
Prediction_Accuracy=71.43%
Average_Accuracy(average_precision)=83.02%
Standard_Deviation=0.094
Scores(average_precision)=[0.852 0.693 0.821 0.911 0.948 0.871 0.71  0.826 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[31 21

### Gaussian Process Classifier

In [104]:
gpc_rbf_clf = GaussianProcessClassifier(n_jobs=-2, max_iter_predict=100, n_restarts_optimizer=10,
                                        random_state=9).fit(X_train, y_train)
gpc_rbf_score = cross_validation_process(gpc_rbf_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=79.51%
Standard_Deviation=0.135
Scores(average_precision)=[0.828 0.609 0.775 1.    0.931 0.659 0.808 0.709 0.821 0.605 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[39 13]
 [17 43]]
Prediction_Accuracy=73.21%


### Logistic Regression

In [105]:
lgst_reg_clf = LogisticRegression(penalty='l2', class_weight='balanced', random_state=9, 
                                  solver='newton-cg', n_jobs=-2, multi_class='auto').fit(X_train, y_train)

lgst_reg_score = cross_validation_process(lgst_reg_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=82.11%
Standard_Deviation=0.113
Scores(average_precision)=[0.811 0.649 0.896 0.931 0.931 0.911 0.71  0.761 0.76  0.673 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[38 14]
 [16 44]]
Prediction_Accuracy=73.21%


### Logistic Regression CV

Best results with:

- Cs = 10, cv = 6
- Cs = 16, cv = 4
- Cs = 19, cv = 6
- Cs = 19, cv = 12
- Cs = 25, cv = 6
- Cs = 25, cv = 12

In [106]:
Cs_cv = {10: 6, 16: 4, 19: [6, 12], 25: [6, 12]}
for k, v in Cs_cv.items():
    if type(v) != list:
        lgst_reg_cv_clf = LogisticRegressionCV(Cs=k, penalty='l2', cv=v,
                                               class_weight='balanced', random_state=9,
                                               solver='newton-cg', n_jobs=-2).fit(X_train, y_train)
        lgst_reg_cv_score = cross_validation_process(
            lgst_reg_cv_clf, X_test, y_test, cv=11)
    else:
        for num in v:
            lgst_reg_cv_clf = LogisticRegressionCV(Cs=k, penalty='l2', cv=num,
                                                   class_weight='balanced', random_state=9,
                                                   solver='newton-cg', n_jobs=-2).fit(X_train, y_train)
            lgst_reg_cv_score = cross_validation_process(
                lgst_reg_cv_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=83.2%
Standard_Deviation=0.097
Scores(average_precision)=[0.841 0.677 0.863 0.911 0.948 0.876 0.71  0.826 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[38 14]
 [16 44]]
Prediction_Accuracy=73.21%
Average_Accuracy(average_precision)=81.74%
Standard_Deviation=0.119
Scores(average_precision)=[0.841 0.677 0.863 0.911 0.948 0.876 0.71  0.826 0.76  0.579 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[35 17]
 [17 43]]
Prediction_Accuracy=69.64%
Average_Accuracy(average_precision)=83.02%
Standard_Deviation=0.097
Scores(average_precision)=[0.822 0.677 0.863 0.911 0.948 0.876 0.71  0.826 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[35 17]
 [17 43]]
Prediction_Accuracy=69.64%
Average_Accuracy(average_precision)=81.61%
Standard_Deviation=0.122
Scores(average_precision)=[0.841 0.677 0.863 0.911 0.948 0.876 0.71  0.826 0.76  0.564 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[35 17

### Ada Boost Classifier 

Best results with:

- n_estimators=235, learning_rate=1.442
- n_estimators=52, learning_rate=0.155
- n_estimators=274, learning_rate=0.013
- n_estimators=162, learning_rate=0.767

In [107]:
n_estimators_learning_rate = {235: 1.442, 52:0.155, 274:0.013, 162:0.767}
for k, v in n_estimators_learning_rate.items():
    ada_clf = AdaBoostClassifier(n_estimators=k, learning_rate=v, 
                                 random_state=9).fit(X_train, y_train)
    ada_scores = cross_validation_process(ada_clf, X_test, y_test, cv=5)

Average_Accuracy(average_precision)=72.98%
Standard_Deviation=0.08
Scores(average_precision)=[0.644 0.822 0.79  0.623 0.769]
Feature importance = [0.01702128 0.85106383 0.00425532 0.00851064 0.00425532 0.00425532
 0.00425532 0.         0.00425532 0.         0.00851064 0.01276596
 0.         0.         0.         0.01276596 0.00851064 0.00425532
 0.00425532 0.00425532 0.00425532 0.00425532 0.00425532 0.00425532
 0.         0.00425532 0.00425532 0.         0.01276596 0.00425532
 0.00425532]
Prediction_Confusion_Matrix=
[[40 12]
 [14 46]]
Prediction_Accuracy=76.79%
Average_Accuracy(average_precision)=78.4%
Standard_Deviation=0.063
Scores(average_precision)=[0.697 0.838 0.765 0.871 0.749]
Feature importance = [0.09615385 0.65384615 0.         0.         0.         0.
 0.01923077 0.         0.         0.         0.         0.07692308
 0.         0.         0.         0.         0.07692308 0.
 0.         0.         0.05769231 0.         0.         0.
 0.         0.         0.         0.     

### SGD Classifier

Best results with:

- max_iter = 28782, n_iter_no_change = 50
- max_iter = 32421, n_iter_no_change = 54
- max_iter = 43631, n_iter_no_change = 74
- max_iter = 37278, n_iter_no_change = 70
- max_iter = 38125, n_iter_no_change = 122

In [108]:
max_iter_no_change = {28782: 50, 32421: 54, 43631: 74, 37278: 70, 38125: 122}
for k, v in max_iter_no_change.items():
    SGD_clf = SGDClassifier(loss='squared_hinge', max_iter=k, shuffle=False,
                            n_jobs=-2, random_state=9, n_iter_no_change=v,
                            class_weight='balanced').fit(X_train, y_train)

    SGD_score = cross_validation_process(SGD_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=82.25%
Standard_Deviation=0.13
Scores(average_precision)=[0.822 0.633 0.933 1.    0.915 0.903 0.71  0.673 0.786 0.673 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[40 12]
 [20 40]]
Prediction_Accuracy=71.43%
Average_Accuracy(average_precision)=82.25%
Standard_Deviation=0.13
Scores(average_precision)=[0.822 0.633 0.933 1.    0.915 0.903 0.71  0.673 0.786 0.673 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[40 12]
 [20 40]]
Prediction_Accuracy=71.43%
Average_Accuracy(average_precision)=82.39%
Standard_Deviation=0.127
Scores(average_precision)=[0.822 0.649 0.924 1.    0.915 0.911 0.71  0.673 0.786 0.673 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[40 12]
 [19 41]]
Prediction_Accuracy=72.32%
Average_Accuracy(average_precision)=82.17%
Standard_Deviation=0.129
Scores(average_precision)=[0.822 0.633 0.924 1.    0.915 0.903 0.71  0.673 0.786 0.673 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[40 12]

### Extra Trees Classifier

In [109]:
XTsC_clf = ExtraTreesClassifier(n_estimators=1000, criterion='entropy',  n_jobs=-2, 
                                random_state=9, class_weight='balanced').fit(X_train, y_train)
XTsC_score = cross_validation_process(XTsC_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=70.01%
Standard_Deviation=0.141
Scores(average_precision)=[0.821 0.594 0.679 0.826 0.836 0.563 0.711 0.521 0.789 0.458 0.903]
Feature importance = [0.03060234 0.65005562 0.01421729 0.01500371 0.00488075 0.00121955
 0.0022092  0.00219584 0.00531976 0.00849126 0.00764247 0.0102056
 0.01037916 0.0116754  0.00861654 0.01122099 0.00809361 0.01307338
 0.00941251 0.00947067 0.00679895 0.00917978 0.00820033 0.0080446
 0.00788828 0.02442886 0.02262717 0.02160814 0.01647008 0.01916307
 0.02160509]
Prediction_Confusion_Matrix=
[[38 14]
 [20 40]]
Prediction_Accuracy=69.64%


### Random Forest Classifier

In [110]:
rand_frst_clf = RandomForestClassifier(n_estimators=1000, criterion='entropy', n_jobs=-2, 
                                       random_state=9).fit(X_train, y_train)

rand_frst_score = cross_validation_process(rand_frst_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=76.6%
Standard_Deviation=0.15
Scores(average_precision)=[0.828 0.577 0.811 0.872 0.948 0.796 0.63  0.609 0.877 0.511 0.967]
Feature importance = [0.03802654 0.5593087  0.01573585 0.01968121 0.00611734 0.00105308
 0.00208805 0.0027664  0.00573028 0.01198725 0.01107348 0.01415184
 0.0127006  0.0136036  0.01277841 0.01410468 0.0124786  0.01728935
 0.01384796 0.01439999 0.01200993 0.01266845 0.01016387 0.0106572
 0.01053087 0.02777376 0.02634397 0.02301732 0.02126997 0.02208004
 0.02456141]
Prediction_Confusion_Matrix=
[[38 14]
 [17 43]]
Prediction_Accuracy=72.32%


### Ridge Classifier

Best results with:

- alpha = 10.13
- alpha = 7.37
- alpha = 13.69

In [111]:
alphas = [10.13, 7.37, 13.69]
for a in alphas:
    ridge_clf = RidgeClassifier(alpha=a, class_weight='balanced', solver='auto',
                                random_state=9).fit(X_train, y_train)
    ridge_score = cross_validation_process(ridge_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=83.44%
Standard_Deviation=0.104
Scores(average_precision)=[0.822 0.676 0.924 0.931 0.931 0.911 0.71  0.775 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[36 16]
 [15 45]]
Prediction_Accuracy=72.32%
Average_Accuracy(average_precision)=82.91%
Standard_Deviation=0.11
Scores(average_precision)=[0.822 0.676 0.896 0.931 0.931 0.911 0.71  0.825 0.76  0.659 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[36 16]
 [15 45]]
Prediction_Accuracy=72.32%
Average_Accuracy(average_precision)=83.67%
Standard_Deviation=0.104
Scores(average_precision)=[0.863 0.665 0.924 0.911 0.931 0.911 0.71  0.789 0.76  0.739 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[36 16]
 [14 46]]
Prediction_Accuracy=73.21%


### Ridge Classifier CV

In [112]:
ridge_cv_clf = RidgeClassifierCV(scoring='average_precision', cv=20,
                                 class_weight='balanced').fit(X_train, y_train)
ridge_cv_score = cross_validation_process(ridge_cv_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=79.81%
Standard_Deviation=0.136
Scores(average_precision)=[0.822 0.719 0.683 0.944 0.933 0.925 0.686 0.775 0.76  0.531 1.   ]
No Feature Importances
Prediction_Confusion_Matrix=
[[36 16]
 [15 45]]
Prediction_Accuracy=72.32%


### K Neighbors Classifier

Best results with:

- n_neighbors = 19, leaf_size = 28
- n_neighbors = 17, leaf_size = 135
- n_neighbors = 19, leaf_size = 88
- n_neighbors = 14, leaf_size = 88
- n_neighbors = 18, leaf_size = 88

In [113]:
n_neighbors_leaf_size = {19:[28, 88], 17:88, 14:88, 18:88}
for k, v in n_neighbors_leaf_size.items():
    if type(v) != list:
        KNN_clf = KNeighborsClassifier(n_neighbors=k, leaf_size=v, n_jobs=-2).fit(X_train, y_train)
        KNN_score = cross_validation_process(KNN_clf, X_test, y_test, cv=11)
    else:
        for num in v:
            KNN_clf = KNeighborsClassifier(n_neighbors=k, leaf_size=num, n_jobs=-2).fit(X_train, y_train)
            KNN_score = cross_validation_process(KNN_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=78.7%
Standard_Deviation=0.111
Scores(average_precision)=[0.821 0.584 0.713 0.948 0.85  0.886 0.66  0.792 0.786 0.683 0.933]
No Feature Importances
Prediction_Confusion_Matrix=
[[37 15]
 [16 44]]
Prediction_Accuracy=72.32%
Average_Accuracy(average_precision)=79.23%
Standard_Deviation=0.084
Scores(average_precision)=[0.821 0.695 0.713 0.948 0.817 0.876 0.696 0.792 0.786 0.683 0.887]
No Feature Importances
Prediction_Confusion_Matrix=
[[39 13]
 [15 45]]
Prediction_Accuracy=75.0%
Average_Accuracy(average_precision)=80.29%
Standard_Deviation=0.118
Scores(average_precision)=[0.843 0.605 0.78  0.952 0.877 0.836 0.676 0.792 0.883 0.62  0.967]
No Feature Importances
Prediction_Confusion_Matrix=
[[38 14]
 [14 46]]
Prediction_Accuracy=75.0%
Average_Accuracy(average_precision)=79.57%
Standard_Deviation=0.111
Scores(average_precision)=[0.867 0.64  0.863 0.976 0.836 0.786 0.616 0.792 0.836 0.642 0.9  ]
No Feature Importances
Prediction_Confusion_Matrix=
[[41 11]


### Multi-layer Perceptron classifier

In [114]:
MLP_clf = MLPClassifier(hidden_layer_sizes=(200,), activation='logistic', solver='lbfgs', 
                        alpha=0.0001, batch_size=8, learning_rate='constant', max_iter=500, 
                        shuffle=False, random_state=9, validation_fraction=0.05, 
                        n_iter_no_change=30).fit(X_train, y_train)

MLP_score = cross_validation_process(MLP_clf, X_test, y_test, cv=11)

Average_Accuracy(average_precision)=74.32%
Standard_Deviation=0.146
Scores(average_precision)=[0.735 0.549 0.668 0.813 0.933 0.925 0.593 0.811 0.71  0.511 0.927]
No Feature Importances
Prediction_Confusion_Matrix=
[[37 15]
 [15 45]]
Prediction_Accuracy=73.21%


In [18]:
# classification_scoring = ['accuracy', 'balanced_accuracy', 'average_precision',
#                           'brier_score_loss', 'f1', 'f1_micro', 'f1_macro',
#                           'f1_weighted', 'neg_log_loss', 'precision',
#                           'recall', 'roc_auc']

In [19]:
# classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="linear", C=0.025),
#     SVC(gamma=2, C=1),
#     GaussianProcessClassifier(1.0 * RBF(1.0)),
#     DecisionTreeClassifier(max_depth=5),
#     RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
#     MLPClassifier(alpha=1),
#     AdaBoostClassifier(),
#     GaussianNB(),
#     QuadraticDiscriminantAnalysis()]

In [ ]:
# clf1 = LogisticRegression(solver='lbfgs', multi_class='multinomial',
#                           random_state=1)
# clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
# clf3 = GaussianNB()

# eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

# for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
#     scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
#     print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

In [ ]:
# clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
#     random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = RandomForestClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean() > 0.999

In [ ]:
# est = GradientBoostingRegressor
# mean_squared_error(y_test, est.predict(X_test))  
# clf.score(X_test, y_test)