In [8]:
import pandas as pd
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import *

from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OutputCodeClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier

from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

from sklearn.neighbors import KDTree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import RadiusNeighborsClassifier

from sklearn.neural_network import MLPClassifier

from sklearn.semi_supervised import LabelPropagation
from sklearn.semi_supervised import LabelSpreading

from sklearn.svm import LinearSVC

from df_functions import *

In [9]:
df = pd.read_csv('../data/df_for_model.csv')

In [10]:
X_train, X_test, y_train, y_test = get_Xy_train_test(df)

y Shape: (2076,)
X Shape: (2076, 31)
X_train Shape: (1908, 31)
X_test Shape: (168, 31)
y_train Shape: (1908,)
y_test Shape: (168,)


/home/guess/lots-of-data/src/df_functions.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [19]:
LDA_clf = LinearDiscriminantAnalysis().fit(X_train, y_train)
LDA_scores = cross_validation_process(LDA_clf, X_test, y_test)

Average Accuracy(average_precision) = 73.52%

Standard Deviation = 0.085

Scores(average_precision):
 [0.65976518 0.80821992 0.68739762 0.86407629 0.6565283 ]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.72      0.67      0.70        86
         1.0       0.68      0.73      0.71        82

   micro avg       0.70      0.70      0.70       168
   macro avg       0.70      0.70      0.70       168
weighted avg       0.70      0.70      0.70       168


confusion_matrix:
[[58 28]
 [22 60]]

confusion_matrix accuracy: 70.23809523809523%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [20]:
QDA_clf = QuadraticDiscriminantAnalysis().fit(X_train, y_train)
QDA_scores = cross_validation_process(QDA_clf, X_test, y_test)

Average Accuracy(average_precision) = 51.65%

Standard Deviation = 0.086

Scores(average_precision):
 [0.43476088 0.47658129 0.56672311 0.66113798 0.44317908]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        86
         1.0       0.49      1.00      0.66        82

   micro avg       0.49      0.49      0.49       168
   macro avg       0.24      0.50      0.33       168
weighted avg       0.24      0.49      0.32       168


confusion_matrix:
[[ 0 86]
 [ 0 82]]

confusion_matrix accuracy: 48.80952380952381%
-----------------------------------------------------------------------


/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/guess/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:686: UserWarning: Variables are collinear
  warnings.warn("Variables are coll

In [21]:
ada_clf = AdaBoostClassifier().fit(X_train, y_train)
ada_scores = cross_validation_process(ada_clf, X_test, y_test)

Average Accuracy(average_precision) = 76.09%

Standard Deviation = 0.02

Scores(average_precision):
 [0.73777237 0.74302032 0.75430289 0.78596172 0.78353113]

Classification Report:
              precision    recall  f1-score   support

         0.0       0.71      0.78      0.74        86
         1.0       0.74      0.67      0.71        82

   micro avg       0.73      0.73      0.73       168
   macro avg       0.73      0.72      0.72       168
weighted avg       0.73      0.73      0.73       168


confusion_matrix:
[[67 19]
 [27 55]]

confusion_matrix accuracy: 72.61904761904762%
-----------------------------------------------------------------------


In [ ]:
XTsC_clf = ExtraTreesClassifier().fit(X_train, y_train)
XTsC_score = cross_validation_process(XTsC_clf, X_test, y_test)

In [ ]:
grad_boost_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1,
                           max_depth=1, random_state=0, loss='ls').fit(X_train, y_train)
grad_boost_score = cross_validation_process(grad_boost_clf, X_test, y_test)

In [ ]:
rand_frst_clf = RandomForestClassifier(n_estimators=10).fit(X_train, y_train)
rand_frst_score = cross_validation_process(rand_frst_clf, X_test, y_test)

In [ ]:
gpc_rbf_clf = GaussianProcessClassifier(n_jobs=-2, max_iter_predict=100).fit(X_train, y_train)
gpc_rbf_score = cross_validation_process(gpc_rbf_clf, X_test, y_test)

In [ ]:
lgst_reg_clf = LogisticRegression().fit(X_train, y_train)
lgst_reg_score = cross_validation_process(lgst_reg_clf, X_test, y_test)

In [ ]:
lgst_reg_cv_clf = LogisticRegressionCV().fit(X_train, y_train)
lgst_reg_cv_score = cross_validation_process(lgst_reg_cv_clf, X_test, y_test)

In [ ]:
ridge_clf = RidgeClassifier().fit(X_train, y_train)
ridge_score = cross_validation_process(ridge_clf, X_test, y_test)

In [ ]:
ridge_cv_clf = RidgeClassifierCV().fit(X_train, y_train)
ridge_cv_score = cross_validation_process(ridge_cv_clf, X_test, y_test)

In [ ]:
SGD_clf = SGDClassifier().fit(X_train, y_train)
SGD_score = cross_validation_process(SGD_clf, X_test, y_test)

In [ ]:
kf_clf = KFold().fit(X_train, y_train)
kf_score = cross_validation_process(kf_clf, X_test, y_test)

In [ ]:
ovo_clf = OneVsOneClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
ovo_score = cross_validation_process(ovo_clf, X_test, y_test)

In [ ]:
ovr_clf = OneVsRestClassifier(LinearSVC(random_state=0)).fit(X_train, y_train)
ovr_score = cross_validation_process(ovr_clf, X_test, y_test)

In [ ]:
OC_clf = OutputCodeClassifier().fit(X_train, y_train)
OC_score = cross_validation_process(OC_clf, X_test, y_test)

In [ ]:
dec_tree_clf = DecisionTreeClassifier().fit(X_train, y_train)
dec_tree_score = cross_validation_process(dec_tree_clf, X_test, y_test)

In [ ]:
ET_clf = ExtraTreeClassifier().fit(X_train, y_train)
ET_score = cross_validation_process(ET_clf, X_test, y_test)

In [ ]:
brnl_clf = BernoulliNB().fit(X_train, y_train)
brnl_score = cross_validation_process(brnl_clf, X_test, y_test)

In [ ]:
gaussian_nb_clf = GaussianNB().fit(X_train, y_train)
gaussian_nb_score = cross_validation_process(gaussian_nb_clf, X_test, y_test)

In [11]:
multinomial_nb_clf = MultinomialNB(alpha=10).fit(X_train, y_train)
ml_nb_scores = cross_validation_process(multinomial_nb_clf, X_test, y_test)

MultinomialNB(alpha=10, class_prior=None, fit_prior=True)

In [ ]:
KDT_clf = KDTree().fit(X_train, y_train)
KDT_score = cross_validation_process(KDT_clf, X_test, y_test)

In [ ]:
KNN_clf = KNeighborsClassifier().fit(X_train, y_train)
KNN_score = cross_validation_process(KNN_clf, X_test, y_test)

In [ ]:
NC_clf = NearestCentroid().fit(X_train, y_train)
NC_score = cross_validation_process(NC_clf, X_test, y_test)

In [ ]:
RN_clf = RadiusNeighborsClassifier().fit(X_train, y_train)
RN_score = cross_validation_process(RN_clf, X_test, y_test)

In [ ]:
MLP_clf = MLPClassifier(solver='lbfgs', random_state=1).fit(X_train, y_train)
MLP_score = cross_validation_process(MLP_clf, X_test, y_test)

In [ ]:
LP_clf = LabelPropagation().fit(X_train, y_train)
LP_score = cross_validation_process(LP_clf, X_test, y_test)

In [ ]:
LS_clf = LabelSpreading().fit(X_train, y_train)
LS_score = cross_validation_process(LS_clf, X_test, y_test)

In [ ]:
# classification_scoring = ['accuracy', 'balanced_accuracy', 'average_precision',
#                           'brier_score_loss', 'f1', 'f1_micro', 'f1_macro',
#                           'f1_weighted', 'neg_log_loss', 'precision',
#                           'recall', 'roc_auc']

In [ ]:
# classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="linear", C=0.025),
#     SVC(gamma=2, C=1),
#     GaussianProcessClassifier(1.0 * RBF(1.0)),
#     DecisionTreeClassifier(max_depth=5),
#     RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
#     MLPClassifier(alpha=1),
#     AdaBoostClassifier(),
#     GaussianNB(),
#     QuadraticDiscriminantAnalysis()]

In [ ]:
# clf1 = LogisticRegression(solver='lbfgs', multi_class='multinomial',
#                           random_state=1)
# clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
# clf3 = GaussianNB()

# eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

# for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
#     scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
#     print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

In [ ]:
# clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
#     random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = RandomForestClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean() > 0.999

In [ ]:
# est = GradientBoostingRegressor
# mean_squared_error(y_test, est.predict(X_test))  
# clf.score(X_test, y_test)