# Running all Classification Models to get the best predictions
## Then, moving on to Neural Networks to get "Better Predictions"

### Ran all the models. Deleting these:
1. __Multinomial Naive-Bayes__
> __Code__<br>
>multinomial_nb_clf = MultinomialNB(alpha=1).fit(X_train, y_train)<br>
>ml_nb_scores = cross_validation_process(multinomial_nb_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 46.67%
Scores(average_precision) = 0.459, 0.445, 0.535, 0.499, 0.417, 
                            0.378, 0.641, 0.542, 0.520, 0.377, 
                            0.322
Confusion_matrix = | 45 | 36 |
                   | 29 | 46 |
Confusion_matrix accuracy = 58.33%`

2. __Gaussian Naive-Bayes__

> __Code__<br>
>gaussian_nb_clf = GaussianNB().fit(X_train, y_train)<br>
>gaussian_nb_score = cross_validation_process(gaussian_nb_clf, X_test, y_test)

`Average Accuracy(average_precision) = 46.16%
Scores(average_precision):, 0.460, 0.426, 0.562, 0.459, 0.442,
                            0.408, 0.617, 0.513, 0.508, 0.365,
                            0.319
confusion_matrix = | 3 | 78 |
                   | 0 | 75 |
confusion_matrix accuracy: 50.00%`

3. __One Vs Rest Classifier__

> __Code__<br>
>ovr_clf = OneVsRestClassifier(LinearSVC(penalty='l2', loss='hinge', dual=True, 
                                        C=32.0, random_state=9)).fit(X_train, y_train)<br>
>ovr_score = cross_validation_process(ovr_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 53.73%
Scores(average_precision) = 0.468, 0.488, 0.570, 0.517, 0.554,
                            0.453, 0.876, 0.613, 0.699, 0.356,
                            0.315
confusion_matrix = | 81 | 0 |
                   | 75 | 0 |
confusion_matrix accuracy = 51.92%`

4. __One Vs One Classifier__

> __Code__<br>
ovo_clf = OneVsOneClassifier(LinearSVC(penalty='l2', loss='hinge', dual=True, 
                                       C=32.0, class_weight='balanced', 
                                       random_state=9)).fit(X_train, y_train)<br>
>ovo_score = cross_validation_process(ovo_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 53.73%
Scores(average_precision) = 0.468, 0.488, 0.570, 0.517, 0.554,
                            0.453, 0.876, 0.613, 0.699, 0.356,
                            0.315
confusion_matrix = | 81 | 0 |
                   | 75 | 0 |
confusion_matrix accuracy = 51.92%`

5. __Bernoulli Naive-Bayes__

> __Code__<br>
>brnl_clf = BernoulliNB().fit(X_train, y_train)<br>
>brnl_score = cross_validation_process(brnl_clf, X_test, y_test)

`Average Accuracy(average_precision) = 48.87%
Scores(average_precision) = 0.465, 0.465, 0.576, 0.502, 0.464,
                            0.399, 0.695, 0.579, 0.517, 0.362,
                            0.350
confusion_matrix = | 43 | 38 |
                   | 32 | 43 |
confusion_matrix accuracy: 55.13%`

6. __Decision Tree Classifier__

> __Code__<br>
>dec_tree_clf = DecisionTreeClassifier().fit(X_train, y_train)<br>
>dec_tree_score = cross_validation_process(dec_tree_clf, X_test, y_test)

`Average Accuracy(average_precision) = 56.05%
Scores(average_precision) = 0.580, 0.427, 0.581, 0.429, 0.540,
                            0.700, 0.738, 0.468, 0.500, 0.531,
                            0.672
confusion_matrix = | 44 | 37 |
                   | 27 | 48 |
confusion_matrix accuracy: 58.97%`

7. __Extra Tree Classifier__

> __Code__<br>
>ET_clf = ExtraTreeClassifier(criterion='entropy', random_state=9, 
                             class_weight='balanced').fit(X_train, y_train)<br>
>ET_score = cross_validation_process(ET_clf, X_test, y_test)

`Average Accuracy(average_precision) = 51.59%
Scores(average_precision) = 0.644, 0.415, 0.454, 0.481, 0.500,
                            0.586, 0.653, 0.539, 0.540, 0.419,
                            0.445
confusion_matrix = | 47 | 34 |
                   | 28 | 47 |
confusion_matrix accuracy: 60.26%`

8. __Gradient Boosting Classifier__

> __Code__<br>
>grad_boost_clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=.1, 
                                            max_depth=500000, random_state=9, 
                                            n_iter_no_change=100).fit(X_train, y_train)<br>
>grad_boost_score = cross_validation_process(grad_boost_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 73.26%
Scores(average_precision) = 0.666, 0.395, 0.818, 0.759, 0.724,
                            0.757, 0.877, 0.733, 0.704, 0.695,
                            0.931
confusion_matrix = | 48 | 33 |
                   | 27 | 48 |
confusion_matrix accuracy: 61.54%`

9. __Random Forest Classifier__

> __Code__<br>
>rand_frst_clf = RandomForestClassifier(n_estimators=100, criterion='entropy', n_jobs=-2, 
                                       random_state=9).fit(X_train, y_train)<br>
>rand_frst_score = cross_validation_process(rand_frst_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 73.66%
Scores(average_precision) = 0.761, 0.638, 0.818, 0.678, 0.557,
                            0.811, 0.927, 0.775, 0.773, 0.623,
                            0.739
confusion_matrix = | 53 | 28 |
                   | 23 | 52 |
confusion_matrix accuracy = 67.31%`

10. __Extra Trees Classifier__

> __Code__<br>
>XTsC_clf = ExtraTreesClassifier(n_estimators=1000, criterion='entropy',  n_jobs=-2, 
                                random_state=9, class_weight='balanced').fit(X_train, y_train)<br>
>XTsC_score = cross_validation_process(XTsC_clf, X_test, y_test, cv=11)

`Average Accuracy(average_precision) = 67.23%
Scores(average_precision) = 0.758, 0.536, 0.779, 0.641, 0.593,
                            0.786, 0.792, 0.556, 0.596, 0.505,
                            0.855
confusion_matrix = | 53 | 28 |
                   | 22 | 53 |
confusion_matrix accuracy = 67.95%`

In [77]:
import pandas as pd
import numpy as np

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import RidgeClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.linear_model import SGDClassifier

from sklearn.metrics import *

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

from sklearn.tree import DecisionTreeClassifier

from sklearn.neighbors import KDTree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import NearestCentroid
from sklearn.neighbors import RadiusNeighborsClassifier

from sklearn.neural_network import MLPClassifier

from sklearn.svm import LinearSVC

from df_functions import *

from warnings import filterwarnings
filterwarnings('ignore')

In [78]:
df = pd.read_csv('../data/df_for_model.csv')

In [164]:
X_train, X_test, y_train, y_test = get_Xy_train_test(df)

y Shape: (2076,)
X Shape: (2076, 31)
X_train Shape: (1997, 31)
X_test Shape: (79, 31)
y_train Shape: (1997,)
y_test Shape: (79,)


### Linear Discriminant Analysis

In [175]:
LDA_clf = LinearDiscriminantAnalysis(solver = 'lsqr', shrinkage='auto').fit(X_train, y_train)
LDA_scores = cross_validation_process(LDA_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 79.39%
Standard Deviation = 0.171
Scores(average_precision) = [0.83  1.    0.732 0.917 0.679 1.    0.817 0.56  0.476 0.722 1.   ]
Prediction Confusion Matrix = 
[[24 13]
 [ 9 33]]
Prediction Accuracy: 72.15%


### Quadratic Discriminant Analysis

In [176]:
QDA_clf = QuadraticDiscriminantAnalysis(reg_param=0.86).fit(X_train, y_train)
QDA_scores = cross_validation_process(QDA_clf, X_test, y_test, cv=10)

Average Accuracy(average_precision) = 82.16%
Standard Deviation = 0.172
Scores(average_precision) = [0.876 1.    0.56  1.    0.679 0.854 0.888 0.493 0.917 0.95 ]
Prediction Confusion Matrix = 
[[25 12]
 [ 9 33]]
Prediction Accuracy: 73.42%


### Gaussian Process Classifier

In [177]:
gpc_rbf_clf = GaussianProcessClassifier(n_jobs=-2, max_iter_predict=100, n_restarts_optimizer=10,
                                        random_state=9).fit(X_train, y_train)
gpc_rbf_score = cross_validation_process(gpc_rbf_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 89.26%
Standard Deviation = 0.107
Scores(average_precision) = [0.917 1.    0.817 1.    0.95  0.771 0.679 0.893 0.793 1.    1.   ]
Prediction Confusion Matrix = 
[[27 10]
 [ 9 33]]
Prediction Accuracy: 75.95%


### Logistic Regression

In [178]:
lgst_reg_clf = LogisticRegression(penalty='l2', class_weight='balanced', random_state=9, 
                                  solver='newton-cg', n_jobs=-2, multi_class='auto').fit(X_train, y_train)

lgst_reg_score = cross_validation_process(lgst_reg_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 84.98%
Standard Deviation = 0.125
Scores(average_precision) = [0.854 1.    0.643 0.917 0.679 0.95  0.95  0.804 0.685 0.867 1.   ]
Prediction Confusion Matrix = 
[[26 11]
 [11 31]]
Prediction Accuracy: 72.15%


### Logistic Regression CV

In [179]:
lgst_reg_cv_clf = LogisticRegressionCV(Cs=19, penalty='l2', cv=5,
                                       class_weight='balanced', random_state=9, 
                                       solver='newton-cg', n_jobs=-2).fit(X_train, y_train)
lgst_reg_cv_score = cross_validation_process(lgst_reg_cv_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 83.39%
Standard Deviation = 0.162
Scores(average_precision) = [0.817 1.    0.56  1.    0.679 0.888 1.    0.804 0.56  0.867 1.   ]
Prediction Confusion Matrix = 
[[24 13]
 [11 31]]
Prediction Accuracy: 69.62%


### Ada Boost Classifier 

Best results with:

n_estimators=235, learning_rate=1.442<br>
n_estimators=52, learning_rate=0.155<br>
n_estimators=274, learning_rate=0.013<br>
n_estimators=162, learning_rate=0.767<br>

In [180]:
ada_clf = AdaBoostClassifier(n_estimators=235, learning_rate=1.442, random_state=9).fit(X_train, y_train)
ada_scores = cross_validation_process(ada_clf, X_test, y_test, cv=5)

Average Accuracy(average_precision) = 74.33%
Standard Deviation = 0.16
Scores(average_precision) = [1.    0.811 0.695 0.511 0.7  ]
Prediction Confusion Matrix = 
[[28  9]
 [ 8 34]]
Prediction Accuracy: 78.48%


### SGD Classifier

In [181]:
SGD_clf = SGDClassifier(loss='squared_hinge', max_iter=10000, shuffle=False, 
                        n_jobs=-2, random_state=9, n_iter_no_change=50, 
                        class_weight='balanced').fit(X_train, y_train)

SGD_score = cross_validation_process(SGD_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 85.15%
Standard Deviation = 0.132
Scores(average_precision) = [1.    1.    0.793 0.917 0.804 0.95  0.95  0.804 0.643 0.589 0.917]
Prediction Confusion Matrix = 
[[25 12]
 [ 9 33]]
Prediction Accuracy: 73.42%


### Extra Trees Classifier

In [182]:
XTsC_clf = ExtraTreesClassifier(n_estimators=1000, criterion='entropy',  n_jobs=-2, 
                                random_state=9, class_weight='balanced').fit(X_train, y_train)
XTsC_score = cross_validation_process(XTsC_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 75.75%
Standard Deviation = 0.14
Scores(average_precision) = [0.625 0.95  0.95  0.65  0.771 0.817 0.71  0.768 0.476 0.7   0.917]
Prediction Confusion Matrix = 
[[27 10]
 [14 28]]
Prediction Accuracy: 69.62%


### Random Forest Classifier

In [183]:
rand_frst_clf = RandomForestClassifier(n_estimators=1000, criterion='entropy', n_jobs=-2, 
                                       random_state=9).fit(X_train, y_train)

rand_frst_score = cross_validation_process(rand_frst_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 82.28%
Standard Deviation = 0.149
Scores(average_precision) = [0.854 1.    0.83  1.    0.679 0.854 0.804 0.747 0.476 0.806 1.   ]
Prediction Confusion Matrix = 
[[26 11]
 [11 31]]
Prediction Accuracy: 72.15%


### Ridge Classifier

In [184]:
ridge_clf = RidgeClassifier(alpha=20.0, class_weight='balanced', solver='sparse_cg', 
                            random_state=9).fit(X_train, y_train)
ridge_score = cross_validation_process(ridge_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 87.64%
Standard Deviation = 0.113
Scores(average_precision) = [0.888 1.    0.768 0.917 0.679 0.95  1.    0.888 0.685 0.867 1.   ]
Prediction Confusion Matrix = 
[[23 14]
 [ 8 34]]
Prediction Accuracy: 72.15%


### Ridge Classifier CV

In [185]:
ridge_cv_clf = RidgeClassifierCV(scoring='average_precision', cv=20, class_weight='balanced').fit(X_train, y_train)
ridge_cv_score = cross_validation_process(ridge_cv_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 83.02%
Standard Deviation = 0.164
Scores(average_precision) = [1.    1.    0.75  0.917 0.771 0.888 0.854 0.888 0.476 0.589 1.   ]
Prediction Confusion Matrix = 
[[23 14]
 [ 7 35]]
Prediction Accuracy: 73.42%


### K Neighbors Classifier

In [186]:
for num in range(2,20):
    print(num)
    KNN_clf = KNeighborsClassifier(n_neighbors=num, leaf_size=45, n_jobs=-2).fit(X_train, y_train)
    KNN_score = cross_validation_process(KNN_clf, X_test, y_test, cv=11)

2
Average Accuracy(average_precision) = 78.68%
Standard Deviation = 0.151
Scores(average_precision) = [0.812 0.95  0.608 1.    0.705 0.664 0.733 0.83  0.518 0.833 1.   ]
Prediction Confusion Matrix = 
[[31  6]
 [22 20]]
Prediction Accuracy: 64.56%
3
Average Accuracy(average_precision) = 81.41%
Standard Deviation = 0.17
Scores(average_precision) = [0.875 1.    0.583 1.    0.721 0.643 0.85  0.747 0.536 1.    1.   ]
Prediction Confusion Matrix = 
[[23 14]
 [13 29]]
Prediction Accuracy: 65.82%
4
Average Accuracy(average_precision) = 82.28%
Standard Deviation = 0.155
Scores(average_precision) = [0.917 1.    0.583 1.    0.7   0.768 0.85  0.83  0.536 0.867 1.   ]
Prediction Confusion Matrix = 
[[28  9]
 [18 24]]
Prediction Accuracy: 65.82%
5
Average Accuracy(average_precision) = 82.14%
Standard Deviation = 0.161
Scores(average_precision) = [0.917 1.    0.583 1.    0.679 0.71  0.8   0.888 0.543 0.917 1.   ]
Prediction Confusion Matrix = 
[[27 10]
 [12 30]]
Prediction Accuracy: 72.15%
6
Average

### Multi-layer Perceptron classifier

In [187]:
MLP_clf = MLPClassifier(solver='lbfgs', random_state=9, shuffle=False).fit(X_train, y_train)
MLP_score = cross_validation_process(MLP_clf, X_test, y_test, cv=11)

Average Accuracy(average_precision) = 65.8%
Standard Deviation = 0.16
Scores(average_precision) = [0.771 0.679 0.475 0.525 0.608 1.    0.685 0.622 0.451 0.556 0.867]
Prediction Confusion Matrix = 
[[24 13]
 [11 31]]
Prediction Accuracy: 69.62%


In [68]:
# classification_scoring = ['accuracy', 'balanced_accuracy', 'average_precision',
#                           'brier_score_loss', 'f1', 'f1_micro', 'f1_macro',
#                           'f1_weighted', 'neg_log_loss', 'precision',
#                           'recall', 'roc_auc']

In [69]:
# classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="linear", C=0.025),
#     SVC(gamma=2, C=1),
#     GaussianProcessClassifier(1.0 * RBF(1.0)),
#     DecisionTreeClassifier(max_depth=5),
#     RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
#     MLPClassifier(alpha=1),
#     AdaBoostClassifier(),
#     GaussianNB(),
#     QuadraticDiscriminantAnalysis()]

In [ ]:
# clf1 = LogisticRegression(solver='lbfgs', multi_class='multinomial',
#                           random_state=1)
# clf2 = RandomForestClassifier(n_estimators=50, random_state=1)
# clf3 = GaussianNB()

# eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

# for clf, label in zip([clf1, clf2, clf3, eclf], ['Logistic Regression', 'Random Forest', 'naive Bayes', 'Ensemble']):
#     scores = cross_val_score(clf, X, y, cv=5, scoring='accuracy')
#     print("Accuracy: %0.2f (+/- %0.2f) [%s]" % (scores.mean(), scores.std(), label))

In [ ]:
# clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
#     random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = RandomForestClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean()


# clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
#     min_samples_split=2, random_state=0)
# scores = cross_val_score(clf, X, y, cv=5)
# scores.mean() > 0.999

In [ ]:
# est = GradientBoostingRegressor
# mean_squared_error(y_test, est.predict(X_test))  
# clf.score(X_test, y_test)