In [93]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
plt.style.use('seaborn-white')
%matplotlib inline

## Linear regression

In [94]:
lin_df = pd.read_csv('../data/ddf_final_without_scores.csv')
numeric_predictors = ['elo', 'opp_elo', 'diff', 'color',
                      'game_time', 'start_time', 'weekday', 'day']
X = lin_df[numeric_predictors]
y = np.array(lin_df['result'])

In [95]:
lm = LinearRegression()

In [96]:
lm.fit(X,y.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [97]:
lm.intercept_

array([0.80776137])

In [98]:
lm.coef_

array([[ 3.31424922e-04, -7.04732128e-04,  1.03615705e-03,
         6.70542631e-02,  7.39859891e-05, -2.93919360e-06,
        -2.48166210e-04, -5.84688916e-05]])

In [101]:
lm.predict(np.array(X.loc[505]).reshape(1,-1))

array([[0.39531984]])

In [103]:
cdf.result.loc[505]

0.0

## Logistic Regression

In [104]:
log_df = pd.read_csv('../data/ddf_final_without_scores.csv')
log_df = log_df[log_df['result']!=0.5]
numeric_predictors = ['elo', 'opp_elo', 'diff', 'color',
                      'game_time', 'start_time', 'weekday', 'day']
X = log_df[numeric_predictors]
y = log_df['result']

In [105]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [106]:
lor = LogisticRegression()

In [107]:
lor.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [109]:
lor.predict(X_test)

array([0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [110]:
lor.coef_

array([[ 5.57935888e-03, -6.42870539e-03,  1.20080643e-02,
         4.14265373e-01,  8.69709159e-04, -1.74046997e-05,
         1.03080683e-02,  1.52400715e-04]])

In [111]:
lor.intercept_

array([0.31170342])

In [112]:
lor.score(X_test, y_test)

0.7455516014234875

In [113]:
lor.predict_proba(X_test)

array([[0.53020544, 0.46979456],
       [0.72879969, 0.27120031],
       [0.2477945 , 0.7522055 ],
       ...,
       [0.93506628, 0.06493372],
       [0.02233665, 0.97766335],
       [0.59177502, 0.40822498]])